### ISSUE TITLE
will be helpful if you can provide a step by step tutorial

### ISSUE THREAD

**Issue by ashishprasad001** [hakito/CakePHP-PayPalRest-Plugin#3]
Hi 
It will be very helpful for the community if you can provide a step by step tutorial on how to implement your plugin with cakephp 2.x . Im not able able to understand where to implement the paypal rest sdk in my cakephp application and how.

**Comment by hakito** [comment]
The easiest way is to install it with composer (as described in readme.md). There you also have an example Usage code. What do you think is missing?

**Comment by ashishprasad001** [comment]
Thank you for a quick reply..i have installed the plugin manually..yet im facing this issue 
Error: Call to a member function AddArticle() on a non-object 

i have uploaded the plugin zip in app/Plugin/PayPal directory
I even copied the contents which you gave for bootstrap and routes in my app respective
app/Config/bootstrap.php and app/Config/routes.php page


In my website controller im calling the following code:
$this->PayPal->AddArticle('Item100', '10', '100', 'ID100'); 
        $this->PayPal->Shipping = 123; 
		$okUrl =  Router::url('/paymentOk', true);
		$nOkUrl = Router::url('/paymentFailed', true);
		return $this->PayPal->PaymentRedirect($order['id'], $okUrl, $nOkUrl);   
		

Don't understand where im going wrong please help.. Do i need to instal paypal REST SDk ? 
If yes then please guide how?

**Comment by hakito** [comment]
Yes you need the PayPal REST api as you can see in the composer.json 

`"paypal/rest-api-sdk-php" : ">=1.3.0"`

I really recommend to use composer for the installation. With composer you get all required dependencies and correctly configured autoloaders.

Manuall installation for the PayPal REST SDK is not part of this repository. You will have to manually call the rest sdk autoloader in your bootstrap (I think). https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call
